from __future__ import division
import jmp
import math

#import jmp_score as jmp
from math import *
import numpy as np

""" ==================================================================
 Copyright(C) 2018 SAS Institute Inc.All rights reserved.

 Notice:
 The following permissions are granted provided that the
 above copyright and this notice appear in the score code and
 any related documentation. Permission to copy, modify
 and distribute the score code generated using
 JMP(R) software is limited to customers of SAS Institute Inc. ("SAS")
 and successive third parties, all without any warranty, express or
 implied, or any other obligation by SAS. SAS and all other SAS
 Institute Inc. product and service names are registered
 trademarks or trademarks of SAS Institute Inc. in the USA
 and other countries. Except as contained in this notice,
 the name of the SAS Institute Inc. and JMP shall not be used in
 the advertising or promotion of products or services without
 prior written authorization from SAS Institute Inc.
 ================================================================== """

""" Python code generated by JMP v15.1.0 """


def getModelMetadata():
    return {"creator": u"Fit Nominal Logistic", "modelName": u"", "predicted": u"Prchase (yes/no)",
            "table": u"Space Filling Latin Hypercube", "version": u"15.1.0", "timestamp": u"2020-12-08T08:56:50Z"}


def getInputMetadata():
    return {
        u"% windshield": "float",
        u"Fuel consumotion (km/l)": "float",
        u"Fuel cost (€/iter)": "float",
        u"Height": "float",
        u"Price (€)": "float",
        u"Year": "float"
    }


def getOutputMetadata():
    return {
        u"Prob[no]_1": "float",
        u"Prob[yes]_1": "float",
        u"Most Likely Prchase (yes/no)_1": "str"
    }


def score(indata, outdata):
    # Original name was: 'Lin[no]_1'
    # Lin_no__1
    # _temp_0
    _temp_1 = [0 for i in range(2)]
    _temp_2 = u""

    Lin_no__1 = 400.389457364428 + -0.0496637629531165 * indata[u"% windshield"] + 0.0438458326033747 * indata[
        u"Fuel consumotion (km/l)"] + 3.53646955685314 * indata[u"Fuel cost (€/iter)"] + -0.0958055046356103 * indata[
                    u"Height"] + 0.0000987106990985412 * indata[u"Price (€)"] + -0.193495221339535 * indata[u"Year"]

    outdata[u"Prob[no]_1"] = 1 / (1 + jmp.exp(-(Lin_no__1)))

    outdata[u"Prob[yes]_1"] = 1 / (1 + jmp.exp(Lin_no__1))

    _temp_1[0] = outdata[u"Prob[no]_1"]
    _temp_1[1] = outdata[u"Prob[yes]_1"]
    _temp_0 = jmp.max_array(2, _temp_1)
    if (_temp_0 == 0):
        _temp_2 = u"no"
    elif (_temp_0 == 1):
        _temp_2 = u"yes"
    else:
        _temp_2 = u""
    outdata[u"Most Likely Prchase (yes/no)_1"] = _temp_2

    return outdata[u"Most Likely Prchase (yes/no)_1"]


# python code for demand generation

'''
    Lin_no__1 = 400.389457364428 + -0.0496637629531165 * indata[u"% windshield"] + 0.0438458326033747 * indata[
        u"Fuel consumotion (km/l)"] + 3.53646955685314 * indata[u"Fuel cost (€/iter)"] + -0.0958055046356103 * indata[
                    u"Height"] + 0.0000987106990985412 * indata[u"Price (€)"] + -0.193495221339535 * indata[u"Year"]

    outdata[u"Prob[no]_1"] = 1 / (1 + jmp.exp(-(Lin_no__1)))

    outdata[u"Prob[yes]_1"] = 1 / (1 + jmp.exp(Lin_no__1))

'''

Lin_no__1 = 400.389457364428 + -0.0496637629531165 * (20) + 0.0438458326033747 * (10) + 3.53646955685314 * (1.2) + -0.0958055046356103 * (180) + 0.0000987106990985412 * (40000) + -0.193495221339535 * (2020)


Prob_yes_1 = 1 / (1 + math.exp(Lin_no__1))

print (Prob_yes_1)



